import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import Banner from '@/components/Banner';
import Card from '../components/Card';
import { fetchCoffeeStores } from '@/lib/coffee-stores';

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('this is working');
  };
  return (
    <>
      <Head>
        <title>Coffee Shop Locater</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText={'View stores nearby'}
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="this is header image"
            width={700}
            height={400}
          ></Image>
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
                    }
                    href={`/coffee-store/${coffeeStore.id}`}
                    alt={coffeeStore.id}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const data = await fetchCoffeeStores();
  return {
    props: {
      coffeeStores: data,
    }, // will be passed to the page component as props
  };
}
